# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

COPY requirements-streamlit.txt /app/
RUN pip install -r requirements-streamlit.txt

# Copy the current directory contents into the container at /app
COPY ui.py /app/streamlit_app.py

# Make port 8501 available to the world outside this container
EXPOSE 8501

# Run app.py when the container launches
CMD ["streamlit", "run", "streamlit_app.py"]
